// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function CloseIcon(Props) {
  return React.createElement("svg", {
              className: "close-icon",
              viewBox: "0 0 32 32",
              xmlns: "http://www.w3.org/2000/svg"
            }, React.createElement("title", undefined, "Close"), React.createElement("path", {
                  d: "M27.914 6.914l-2.828-2.828-9.086 9.086-9.086-9.086-2.828 2.828 9.086 9.086-9.086 9.086 2.828 2.828 9.086-9.086 9.086 9.086 2.828-2.828-9.086-9.086z"
                }));
}

var make = CloseIcon;

export {
  make ,
}
/* react Not a pure module */
