// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function DragHandleIcon(Props) {
  return React.createElement("svg", {
              className: "drag-handle-icon",
              viewBox: "0 0 32 32",
              xmlns: "http://www.w3.org/2000/svg"
            }, React.createElement("title", undefined, "Drag Handle"), React.createElement("path", {
                  d: "M2 6h28v4h-28v-4z"
                }), React.createElement("path", {
                  d: "M2 14h28v4h-28v-4z"
                }), React.createElement("path", {
                  d: "M2 22h28v4h-28v-4z"
                }));
}

var make = DragHandleIcon;

export {
  make ,
}
/* react Not a pure module */
