// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function MenuIcon(Props) {
  return React.createElement("svg", {
              className: "menu-icon",
              viewBox: "0 0 32 32",
              xmlns: "http://www.w3.org/2000/svg"
            }, React.createElement("title", undefined, "Menu"), React.createElement("path", {
                  d: "M2 6h28v6h-28zM2 14h28v6h-28zM2 22h28v6h-28z"
                }));
}

var make = MenuIcon;

export {
  make ,
}
/* react Not a pure module */
