// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as Pervasives from "rescript/lib/es6/pervasives.js";
import * as Client from "react-dom/client";

var root = document.querySelector("#app");

if (root == null) {
  Pervasives.failwith("DOM node `#app` not found");
} else {
  Client.createRoot(root).render(React.createElement(App.make, {}));
}

export {
  
}
/* root Not a pure module */
