// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.bs.js";
import * as React from "react";

function Control(props) {
  var className = props.className;
  var className$1 = className !== undefined ? className : "";
  return React.createElement("button", {
              className: Cx.cx([
                    "control",
                    className$1
                  ]),
              style: props.style,
              type: "button",
              onClick: props.onClick,
              onMouseDown: props.onMouseDown,
              onTouchStart: props.onTouchStart
            }, props.children);
}

var make = Control;

export {
  make ,
}
/* react Not a pure module */
