// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Container(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "container"
            }, children);
}

var make = Container;

export {
  make ,
}
/* react Not a pure module */
