// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Container(props) {
  return React.createElement("div", {
              className: "container"
            }, props.children);
}

var make = Container;

export {
  make ,
}
/* react Not a pure module */
