// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function Input(props) {
  var onChange = props.onChange;
  return React.createElement("input", {
              className: "input",
              id: props.id,
              value: props.value,
              onChange: (function ($$event) {
                  Curry._1(onChange, $$event.target.value);
                })
            });
}

var make = Input;

export {
  make ,
}
/* react Not a pure module */
