// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Label(props) {
  return React.createElement("label", {
              className: "label",
              htmlFor: props.htmlFor
            }, props.children);
}

var make = Label;

export {
  make ,
}
/* react Not a pure module */
