// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Label(Props) {
  var htmlFor = Props.htmlFor;
  var children = Props.children;
  return React.createElement("label", {
              className: "label",
              htmlFor: htmlFor
            }, children);
}

var make = Label;

export {
  make ,
}
/* react Not a pure module */
