// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Main(props) {
  return React.createElement("main", undefined, props.children);
}

var make = Main;

export {
  make ,
}
/* react Not a pure module */
