// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Main(Props) {
  var children = Props.children;
  return React.createElement("main", undefined, children);
}

var make = Main;

export {
  make ,
}
/* react Not a pure module */
